### ISSUE TITLE
Fix logo in responsive view

### ISSUE THREAD

**Issue by MukulGaur** [MukulGaur/amusement-park-front-end#4]
The navbar logo on the left is "TOMORROWLAND" but it changes to "LOGO" in a responsive view. The component was taken from MUI.
checkout 'src\components\navbar\Navbar.jsx' for this issue.

Fix it so that it shows "TOMORROWLAND" in all views.

**Comment by agustintrossero** [comment]
hi there, i would like to help you with this

**Comment by MukulGaur** [comment]
Hi @agustintrossero thanks for showing interest in this, I don't have any PR template or contribution guidelines.
Fork the repo and raise a PR will check.
Please mention the issue number in the PR.
